# Gemeinsame Einstellungen für Sensoren und Controller (wird unten mit <<: *app eingefügt)
x-app: &app
  build: .
  image: smartbuilding
  env_file: .env
  environment:
    MQTT_HOST: mqtt-broker
  depends_on:
    - mqtt-broker

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data

  controller:
    <<: *app
    container_name: controller
    command: python controller.py

  sensor-wohnzimmer:
    <<: *app
    container_name: sensor-wohnzimmer
    command: python simulator.py zb-temp-wohnzimmer

  sensor-serverraum:
    <<: *app
    container_name: sensor-serverraum
    command: python simulator.py zb-temp-serverraum

  sensor-garten:
    <<: *app
    container_name: sensor-garten
    command: python simulator.py lora-soil-garten

  sensor-eingang:
    <<: *app
    container_name: sensor-eingang
    command: python simulator.py ble-door-eingang
